---
- name: Install and configure Nginx
  hosts: all
  become: yes  # Use sudo for elevated privileges
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Nginx web server
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Start and enable Nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Allow HTTP traffic on port 80
      ansible.builtin.ufw:
        rule: allow
        port: "80"
        proto: tcp

    - name: Verify Nginx service status
      ansible.builtin.command: systemctl is-active nginx
      register: nginx_status
      changed_when: false

    - name: Display Nginx status output
      ansible.builtin.debug:
        msg: "Nginx is {{ nginx_status.stdout }}"

    - name: Copy custom index.html for AWS
      ansible.builtin.copy:
        src: index-aws.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'
      when: "'aws-app' in inventory_hostname"

    - name: Copy custom index.html for Azure
      ansible.builtin.copy:
        src: index-azure.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'
      when: "'azure-vm' in inventory_hostname"

    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
